services:
  backend:
    build: .
    command: uv run uvicorn src.main:app --workers 4 --forwarded-allow-ips '*' --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - ops_db
    restart: always
    env_file:
      - .env

  ops_db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - "5432"
    ports:
      - 5434:5432

volumes:
  postgres_data:
