"""empty message

Revision ID: e22243ac3a46
Revises: ec08b798e787
Create Date: 2025-04-01 16:57:14.378480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22243ac3a46'
down_revision: Union[str, None] = 'ec08b798e787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'external_file_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('generations', 'storage_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'storage_url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('generations', 'external_file_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
