"""empty message

Revision ID: d920ce3c5070
Revises: e22243ac3a46
Create Date: 2025-04-02 22:12:51.791961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd920ce3c5070'
down_revision: Union[str, None] = 'e22243ac3a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('storage_key', sa.String(length=256), nullable=True))
    op.drop_constraint('generations_storage_url_key', 'generations', type_='unique')
    op.create_unique_constraint(None, 'generations', ['storage_key'])
    op.drop_column('generations', 'storage_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('storage_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generations', type_='unique')
    op.create_unique_constraint('generations_storage_url_key', 'generations', ['storage_url'])
    op.drop_column('generations', 'storage_key')
    # ### end Alembic commands ###
